package br.com.fiap.model;

import java.time.LocalDate;

public class Preset {
	
//	Integrantes:
//	Enrico Thomas Mazelli - 94371
//	João Pedro Marson - 93432
//	Rafael de Lima Souza - 92876
	
//	SQL command:
//	create table Preset (
//	id integer generated by default as identity primary key,
//	nome varchar2(30) not null,
//	body varchar2(20) not null,
//	cor varchar2(20) not null,
//	decal varchar2(20) not null,
//	roda varchar2(20) not null,
//	boost varchar2(20) not null,
//	data_criacao date not null);
	
	private long id;
	private String nome;
	private String body;
	private String cor;
	private String decal;
	private String roda;
	private String boost;
	private LocalDate dataCriacao;
	
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getBody() {
		return body;
	}
	public void setBody(String body) {
		this.body = body;
	}
	public String getCor() {
		return cor;
	}
	public void setCor(String cor) {
		this.cor = cor;
	}
	public String getDecal() {
		return decal;
	}
	public void setDecal(String decal) {
		this.decal = decal;
	}
	public String getRoda() {
		return roda;
	}
	public void setRoda(String roda) {
		this.roda = roda;
	}
	public String getBoost() {
		return boost;
	}
	public void setBoost(String boost) {
		this.boost = boost;
	}
	public LocalDate getDataCriacao() {
		return dataCriacao;
	}
	public void setDataCriacao(LocalDate dataCriacao) {
		this.dataCriacao = dataCriacao;
	}
	
	@Override
	public String toString() {
		return "Preset [id=" + id + ", nome=" + nome + ", body=" + body + ", cor=" + cor + ", decal=" + decal
				+ ", roda=" + roda + ", boost=" + boost + ", dataCriacao=" + dataCriacao + "]";
	}
}
